build:
  image: maven:3.3.3-jdk-8-onbuild
  pull: true
  environment:
  commands:
    - git log | head -n 20
    - mvn clean package
    - mvn spring-boot:run -Drun.arguments="spring.profiles.active=test"
