kind: pipeline
name: default

steps:
- name: build
  image: ubuntu
  commands:
    - git clone https://github.com/sushilkamboj/boottest.git
    - mvn clean package
    - mvn spring-boot:run -Drun.arguments="spring.profiles.active=test"
  when:
    branch:
    - master
    event:
    - pull-reqiest
  username: 
  - from_secret: sushilkamboj
  password:
  - from_secret: Sk@3081974

