kind: pipeline
name: default

steps:
- name: build
  commands:
    - git clone https://github.com/sushilkamboj/boottest.git
    - mvn clean package
    - mvn spring-boot:run -Drun.arguments="spring.profiles.active=test"
